language: cpp
compiler:
  - gcc
# Build MCServer
script: cmake . -DBUILD_TOOLS=1 -DSELF_TEST=1 && make -j 2 && cd MCServer/ && (echo stop | $MCSERVER_PATH)

env:
  global:
    - secure: "WzuO3e3i6afbaogY3lCfCiv2uej6gFk8B8zp0x1FIrpvrRAota9aN1SLy0lBTfvZdhZMR0uI4hOjQWJYW3ePNNUTrQeZOZRVzyAJXiFyA29oQB3TvdA/9GsXtRAV1fjrl/i1KZLbLUDgLy2maLdqWDhz7Mr+Mlpdvwxf2wngigM="
  matrix:
    - TRAVIS_MCSERVER_BUILD_TYPE=RELEASE MCSERVER_PATH=./MCServer

# Notification Settings
notifications:
  email:
    on_success: change
    on_failure: always
    
addons:
  coverity_scan:
    project:
      name: "mc-server/MCServer"
      description: "Your project description here"
    notification_email: work.tycho@gmail.com
    build_command_prepend: cmake . -DBUILD_TOOLS=1 -DSELF_TEST=1
    build_command: make
    branch_pattern: coverity_scan
