language: cpp
compiler:
  - gcc
  - clang

before_install:
  - if [ "$TRAVIS_MCSERVER_BUILD_TYPE" == "COVERAGE" ]; then sudo pip install cpp_coveralls; fi

# Build MCServer
script: ./CIbuild.sh

after_success:
  - ./uploadCoverage.sh

env:
  - global:
    - secure: "WzuO3e3i6afbaogY3lCfCiv2uej6gFk8B8zp0x1FIrpvrRAota9aN1SLy0lBTfvZdhZMR0uI4hOjQWJYW3ePNNUTrQeZOZRVzyAJXiFyA29oQB3TvdA/9GsXtRAV1fjrl/i1KZLbLUDgLy2maLdqWDhz7Mr+Mlpdvwxf2wngigM="
  - TRAVIS_MCSERVER_BUILD_TYPE=RELEASE MCSERVER_PATH=./MCServer
  - TRAVIS_MCSERVER_BUILD_TYPE=DEBUG   MCSERVER_PATH=./MCServer_debug
  - TRAVIS_MCSERVER_BUILD_TYPE=RELEASE TRAVIS_MCSERVER_FORCE32=1 MCSERVER_PATH=./MCServer
  - TRAVIS_MCSERVER_BUILD_TYPE=DEBUG   TRAVIS_MCSERVER_FORCE32=1 MCSERVER_PATH=./MCServer_debug

matrix:
  include:
    - compiler: gcc
      env: TRAVIS_MCSERVER_BUILD_TYPE=COVERAGE   MCSERVER_PATH=./MCServer

# Notification Settings
notifications:
  email:
    on_success: change
    on_failure: always
    
addons:
  coverity_scan:
    project:
      name: "mc-server/MCServer"
      description: "Your project description here"
    notification_email: work.tycho@gmail.com
    build_command_prepend: cmake . -DBUILD_TOOLS=1 -DSELF_TEST=1
    build_command: make
    branch_pattern: coverity_scan
